application: philippp
version: 1
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: todo.py

- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /xml 
  static_dir: xml

- url: /img
  static_dir: img
